name: e-commerce-api
services:
  api:
    container_name: api
    build:
      dockerfile: docker/api/Dockerfile
    environment:
      POSTGRESQL_DB_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_HOST: dragonfly
      REDIS_PORT: 6379

      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_BACKEND_URL: ${CELERY_BACKEND_URL}

      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}

      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}

      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_MAIL: ${SMTP_MAIL}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SERVER: ${SMTP_SERVER}
    depends_on:
      - db
      - dragonfly
    ports:
      - "8000:8000"
    volumes:
      - petstore_static:/app/${STATIC_PATH}
  dragonfly:
    container_name: dragonfly
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ports:
      - "6380:6379"
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - petstore_db_data:/var/lib/postgresql/data
  celery_worker:
    container_name: celery_worker
    build:
      dockerfile: docker/celery-worker/Dockerfile
    command: celery -A src.tasks:celery worker -l info
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_BACKEND_URL: ${CELERY_BACKEND_URL}

      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_MAIL: ${SMTP_MAIL}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SERVER: ${SMTP_SERVER}
    depends_on:
      - api
      - dragonfly
  flower:
    container_name: flower
    build:
      dockerfile: docker/celery-worker/Dockerfile
    command: celery -A src.tasks:celery flower --port=5555
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_BACKEND_URL: ${CELERY_BACKEND_URL}

      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_MAIL: ${SMTP_MAIL}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SERVER: ${SMTP_SERVER}
    depends_on:
      - api
      - dragonfly
      - celery_worker

volumes:
  petstore_db_data:
  petstore_static: