name: petstore
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      POSTGRESQL_DB_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - petstore_static:/app/${STATIC_PATH}
  redis:
    container_name: petstore_redis
    image: redis:latest
    ports:
      - "6380:6379"
#  celery_worker:
#    container_name: celery_worker
#    build:
#      context: .
#      dockerfile: ./docker/celery-worker/Dockerfile
#    command: celery -A src.celery_tasks:celery worker -l info
#    environment:
#      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
#      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
#    depends_on:
#      - api
#      - redis
#  flower:
#    container_name: flower
#    build:
#      context: .
#      dockerfile: ./docker/celery-worker/Dockerfile
#    command: celery -A src.celery_tasks:celery flower --port=5555
#    ports:
#      - "5555:5555"
#    environment:
#      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
#      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
#    depends_on:
#      - api
#      - redis
#      - celery_worker
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - petstore_db_data:/var/lib/postgresql/data

volumes:
  petstore_db_data:
  petstore_static: